config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'dashboard#show'

  resources :hosts, only: %i(index edit update)
  resources :macs, only: %i(edit update)
  resources :wifi_access_points, except: %i(show)

  mount Sidekiq::Web => '/sidekiq'
end

app/models/wifi_access_point.rb
class WifiAccessPoint < ApplicationRecord

  belongs_to :ip
  has_many :wifi_clients

  assignable_values_for :type, default: 'WifiAccessPoint::Fritzbox' do
    %w[WifiAccessPoint::Fritzbox]
  end

  def update_clients!
    WifiClient.transaction do
      clients = get_clients

      macs = clients.map { |c| c[:mac] }
      mac_ids = Mac.where(address: macs).ids

      WifiClient.where.not(mac_id: mac_ids).destroy_all

      clients.each do |client|
        mac = Mac.find_or_initialize_by(address: client[:mac])
        unless mac.persisted?
          mac.host = Host.create!
          mac.save!
        end

        wifi_client = WifiClient.find_or_initialize_by(mac_id: mac.id, wifi_access_point_id: self.id)
        wifi_client.assign_attributes(client.slice(:ssid, :bssid, :frequency, :cipher, :rssi, :rate_up, :rate_down, :props))
        wifi_client.last_seen = Time.now
        wifi_client.save!
      end
    end
  end

  def display_name
    name.presence || ip.mac.host.name.presence || '-'
  end

  def to_s
    display_name
  end

  def password=(password)
    if password.present?
      super(password)
    end
  end

  protected

  def get_clients
    raise NotImplementedError
  end

end

app/models/wifi_access_point/fritzbox.rb
class WifiAccessPoint::Fritzbox < WifiAccessPoint

  validates :password, presence: true

  protected

  def get_clients
    FritzboxWebApi.new(ip.address, password).get_clients
  end

end

app/controllers/wifi_access_points_controller.rb
class WifiAccessPointsController < ApplicationController

  def index
    load_wifi_access_points
  end

  def new
    build_wifi_access_point
  end

  def create
    build_wifi_access_point
    if @wifi_access_point.save
      redirect_to wifi_access_points_path
    else
      render 'new'
    end
  end

  def edit
    load_wifi_access_point
  end

  def update
    load_wifi_access_point
    build_wifi_access_point
    if @wifi_access_point.save
      redirect_to wifi_access_points_path
    else
      render 'edit'
    end
  end

  private

  def load_wifi_access_points
    @wifi_access_points = wifi_access_point_scope.all
    @lose_ips = Ip.where(mac: nil)
  end

  def load_wifi_access_point
    @wifi_access_point ||= wifi_access_point_scope.find(params[:id])
  end

  def build_wifi_access_point
    @wifi_access_point ||= wifi_access_point_scope.build
    @wifi_access_point.attributes = wifi_access_point_params
  end

  def wifi_access_point_params
    wifi_access_point_params = params[:wifi_access_point]
    wifi_access_point_params ? wifi_access_point_params.permit(:ip_id, :name, :password, :type) : {}
  end

  def wifi_access_point_scope
    WifiAccessPoint.all
  end

end

app/views/wifi_access_points/_form.html.haml
= simple_form_for @wifi_access_point, as: :wifi_access_point, url: (@wifi_access_point.persisted? ? wifi_access_point_path(@wifi_access_point) : wifi_access_points_path), html: { 'up-target': 'form' } do |form|

  = form.input :name

  = form.input :type, collection: @wifi_access_point.assignable_types

  = form.association :ip

  = form.input :password

  = cancel_submit_buttons(form)

app/views/wifi_access_points/edit.html.haml
.panel

  .modal-content-wrapper

    %h5 Edit #{@wifi_access_point}
    %br

    = render 'form', wifi_access_point: @wifi_access_point

app/views/wifi_access_points/index.html.haml
.panel.-fullscreen
  %h4.d-inline-block
    Wifi Access Points
  = link_to 'New', new_wifi_access_point_path, class: 'btn btn-success', 'up-modal': '.modal-content-wrapper'


  - @wifi_access_points.each do |wifi_access_point|
    %h5.mt-5
      = wifi_access_point.display_name
      = edit_delete_icons(wifi_access_point)

    %table.table
      %thead
        %tr
          %th Host
          %th Mac
          %th SSID
          %th BSSID
          %th Cipher
          %th Band
          %th Rate Upstream
          %th Rate Downstream
          %th

      %tbody
        - wifi_access_point.wifi_clients.each do |wifi_client|
          %tr
            %td= wifi_client.mac.host.name
            %td= wifi_client.mac.address
            %td= wifi_client.ssid
            %td= wifi_client.bssid
            %td= wifi_client.cipher
            %td= "#{wifi_client.frequency} GHz"
            %td= "#{wifi_client.rate_up} MBits"
            %td= "#{wifi_client.rate_down} MBits"
            %td= wifi_client.props

app/views/wifi_access_points/new.html.haml
.panel

  .modal-content-wrapper

    %h5 Create Wifi Access Point
    %br

    = render 'form', wifi_access_point: @wifi_access_point