config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'dashboard#show'

  resources :hosts, only: %i(index edit update)
  resources :macs, only: %i(edit update)
  resources :wifi_access_points, except: %i(show)

  mount Sidekiq::Web => '/sidekiq'
end

app/models/host.rb
class Host < ApplicationRecord

  has_many :macs, dependent: :destroy

  scope :named, -> { where.not(name: [nil, '']) }

  def to_s
    name
  end

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController

  def index
    @host_lines = []

    host_scope.includes(macs: {ips: :hostnames}).each do |host|
      if host.macs.blank?
        @host_lines << { host: host, mac: nil, ip: nil, hostname: nil }
      else
        host.macs.each do |mac|
          if mac.ips.blank?
            @host_lines << { host: host, mac: mac, ip: nil, hostname: nil }
          else
            mac.ips.each do |ip|
              if ip.hostnames.blank?
                @host_lines << { host: host, mac: mac, ip: ip, hostname: nil }
              else
                ip.hostnames.each do |hostname|
                  @host_lines << { host: host, mac: mac, ip: ip, hostname: hostname }
                end
              end
            end
          end
        end
      end
    end

    Ip.where(mac: nil).includes(:hostnames).each do |ip|
      ip_key = "ip#{ip.id}"
      if ip.hostnames.blank?
        @host_lines << { host: ip_key, mac: ip_key, ip: ip, hostname: nil }
      else
        ip.hostnames.each do |hostname|
          @host_lines << { host: ip_key, mac: ip_key, ip: ip, hostname: hostname }
        end
      end
    end

    @host_lines.sort_by! do |host_line|
      [host_line[:ip]&.address, host_line[:mac].to_s, host_line[:host].to_s].reverse.join
    end
  end

  def edit
    load_host
  end

  def update
    load_host
    build_host
    if @host.save
      redirect_to hosts_path
    else
      render 'edit'
    end
  end

  private

  def load_hosts
    @hosts = Host.all
    @lose_ips = Ip.where(mac: nil)
  end

  def load_host
    @host ||= host_scope.find(params[:id])
  end

  def build_host
    @host ||= host_scope.build
    @host.attributes = host_params
  end

  def host_params
    host_params = params[:host]
    host_params ? host_params.permit(:name) : {}
  end

  def host_scope
    Host.all
  end

end

app/views/hosts/edit.html.haml
.panel
  .edit-host
    %h4 Edit Host

    = simple_form_for @host do |form|

      = form.input :name

      .mt-3
        = link_to 'cancel', _back_url, class: 'btn btn-outline-secondary'
        = form.button :submit, class: 'btn btn-primary'

app/views/hosts/index.html.haml
.panel.-fullscreen
  %h5
    Hosts
  %br

    .host-grid.w-auto
      - @host_lines.each_with_index do |host_line, line_index|
        - host = host_line[:host]
        - mac = host_line[:mac]
        - ip = host_line[:ip]
        - hostname = host_line[:hostname]

        - divider = (host != @host_lines[line_index-1][:host])
        .host-grid--item{ class: ( "-line" if divider && line_index != 0) }
          - if host.is_a?(Host) && divider
            .grid-node
              .grid-node--text= link_to (host.name.presence || '-'), edit_host_path(host), 'up-modal': '.edit-host'

        - divider = (mac != @host_lines[line_index-1][:mac])
        .host-grid--item{ class: ( "-line" if divider && line_index != 0) }
          - if mac.is_a?(Mac) && divider
            .grid-node.-mac
              .grid-node--indicator= last_seen_indicator(mac.last_seen_by_arp)
              .grid-node--text= link_to mac.address_string_with_vendor, edit_mac_path(mac), 'up-modal': '.edit-mac'

        - divider = (ip != @host_lines[line_index-1][:ip])
        .host-grid--item{ class: ( "-line" if  divider && line_index != 0) }
          - if ip && divider
            .grid-node.-ip
              .grid-node--indicator= last_seen_indicator(ip.last_seen_by_ping)
              .grid-node--text= link_to ip.address, '#'
        - divider = (hostname != @host_lines[line_index-1][:hostname])
        .host-grid--item{ class: ( "-line" if divider && line_index != 0) }
          - if hostname
            .grid-node= hostname.name