config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'dashboard#show'

  resources :hosts, only: %i(index edit update)
  resources :macs, only: %i(edit update)
  resources :wifi_access_points, except: %i(show)

  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_menu.html.haml
.menu

  = link_to icon(:dashboard, text: 'Dashboard'), root_path, class: 'menu--item', 'up-target': '.layout--content', 'layout--hide-menu': '', 'up-restore-scroll': true
  = link_to icon(:hosts, text: 'Hosts'), hosts_path, class: 'menu--item', 'up-target': '.layout--content', 'layout--hide-menu': '', 'up-restore-scroll': true
  = link_to icon(:wifi_access_points, text: 'Wifi Access Points'), wifi_access_points_path, class: 'menu--item', 'up-target': '.layout--content', 'layout--hide-menu': '', 'up-restore-scroll': true

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title NetworkDashboard

    %meta(name="viewport" content="width=device-width,initial-scale=1")
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'


  %body
    .layout
      .layout--header-title
        Network Dashboard
      .layout--header-menu
      .layout--header-menu-toggle
        .layout--header-menu-toggle-button(layout--toggle-menu)
          = icon :open_menu
      .layout--menu
        = render 'layouts/menu'
      .layout--content
        = yield